apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-argo-helm-db.fullname" . }}
  labels:
    {{- include "demo-argo-helm-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demo-argo-helm-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-argo-helm-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-argo-helm-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: 
              containerPort: {{ .Values.Deployment.containerPort }}
              env:
              - name: POSTGRES_DB
                value:  {{ .Values.PostgreSQL.postgresqlDatabase }} #  "johndb_k"  # Replace with your desired database name
              - name: POSTGRES_USER
                value: {{ .Values.PostgreSQL.postgresqlUsername }}  # "john_k"  # Replace with your desired PostgreSQL username
              - name: POSTGRES_PASSWORD
                value: {{ .Values.PostgreSQL.postgresqlPassword }}  # "mysql_k"   # Replace with your desired PostgreSQL password
              


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

--- 

