##### working for user = admin-user-default  -n default  all access 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user-default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user-default
  namespace: default
---
########### kubectl  create token admin-user-default  -n default
##########
