##  kubectl create token kb-user -n kb    ##### working code  do not change 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kb-user
  namespace: kb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kb-user
  namespace: kb
---
############## kubectl get pods  --all-namespaces
###  All namespaces  access in UI  
